name: build prject

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up graalvm 17
              uses: actions/setup-java@v4
              with:
                distribution: "graalvm"
                java-version: "17"
                cache: maven
            - name: build and package
              run: chmod +x package.sh;./package.sh
            - name: upload package files
              uses: actions/upload-artifact@v4
              with:
                name: java-package
                path: target/auto_login*.jar